# Generated by Django 2.2.13 on 2020-08-23 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='experience',
            name='exp',
        ),
        migrations.AddField(
            model_name='experience',
            name='title',
            field=models.CharField(default='Title', max_length=200),
        ),
    ]
