# Generated by Django 2.2.12 on 2020-08-26 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0004_auto_20200826_0457'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='Comment_1',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='Comment_2',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='Comment_3',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='Comment_4',
        ),
        migrations.AddField(
            model_name='experience',
            name='comments',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], default='0', max_length=1),
        ),
    ]
