# Generated by Django 2.2.12 on 2020-08-26 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0005_auto_20200826_0650'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='comments',
        ),
    ]
