# Generated by Django 2.2.12 on 2020-08-26 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0006_remove_experience_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='Comment_1',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='experience',
            name='Comment_2',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='experience',
            name='Comment_3',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='experience',
            name='Comment_4',
            field=models.TextField(blank=True, default=''),
        ),
    ]
