# Generated by Django 2.2.12 on 2020-08-26 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0007_auto_20200826_0806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='Comment_1',
            field=models.TextField(blank=True, default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='experience',
            name='Comment_2',
            field=models.TextField(blank=True, default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='experience',
            name='Comment_3',
            field=models.TextField(blank=True, default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='experience',
            name='Comment_4',
            field=models.TextField(blank=True, default='', max_length=250),
        ),
    ]
