# Generated by Django 2.2.12 on 2020-08-26 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0008_auto_20200826_0812'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=200)),
                ('Comment_1', models.CharField(blank=True, default='', max_length=250)),
                ('Comment_2', models.CharField(blank=True, default='', max_length=250)),
                ('Comment_3', models.CharField(blank=True, default='', max_length=250)),
                ('Comment_4', models.CharField(blank=True, default='', max_length=250)),
                ('Comment_5', models.CharField(blank=True, default='', max_length=250)),
                ('Comment_6', models.CharField(blank=True, default='', max_length=250)),
                ('Comment_7', models.CharField(blank=True, default='', max_length=250)),
                ('Comment_8', models.CharField(blank=True, default='', max_length=250)),
                ('Comment_9', models.CharField(blank=True, default='', max_length=250)),
            ],
            options={
                'verbose_name_plural': 'Education',
            },
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=200)),
                ('Comment_1', models.CharField(blank=True, default='', max_length=250)),
                ('Comment_2', models.CharField(blank=True, default='', max_length=250)),
                ('Comment_3', models.CharField(blank=True, default='', max_length=250)),
                ('Comment_4', models.CharField(blank=True, default='', max_length=250)),
            ],
            options={
                'verbose_name': 'Additional skills',
                'verbose_name_plural': 'Additional skills',
            },
        ),
        migrations.AlterModelOptions(
            name='experience',
            options={'verbose_name': 'Work Experience', 'verbose_name_plural': 'Work Experience'},
        ),
        migrations.AlterField(
            model_name='experience',
            name='Comment_1',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='experience',
            name='Comment_2',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='experience',
            name='Comment_3',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='experience',
            name='Comment_4',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
    ]
