# Generated by Django 2.2.12 on 2020-08-26 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0009_auto_20200826_0820'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skills',
            name='title',
        ),
    ]
